### ISSUE TITLE
how to update data

### ISSUE THREAD

**Issue by julienGautier77** [FirebirdSQL/python3-driver#13]
Hello 
i read easly my data but when I tried to update one row of a table but I didn't success  :

update= 'update %s set VALPARAM=%s where IDNAME=%s and IDMODULE=%d and NUMAXIS=%d' % (TABLE_NAME,valPara, IDNAME,IDMODULE,NUMAXIS)

curUpdate = con.cursor()
curUpdate.execute(update)

I think i didn't use the good way 
I someone could explain me how to do 
Thanks in advance

**Comment by pcisar** [comment]
https://firebird-driver.readthedocs.io/en/latest/usage-guide.html#id3
