### ISSUE TITLE
Python 3.11-rc2 error: _decompose no longer available in enum.py

### ISSUE THREAD

**Issue by digitaldutch** [FirebirdSQL/python3-driver#14]
I just tried the driver in the Python 3.11 rc2 and get an error:
```
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\firebird\base\config.py", line 58, in <module>
    from enum import Enum, Flag, _decompose
ImportError: cannot import name '_decompose' from 'enum' (C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\enum.py)
```

The problem is that the _decompose function is no longer available in the 3.11 version of enum.py.

**Comment by pcisar** [comment]
First, this problem is not in driver itself, but in firebird-base package.
Second, fixed was committed to firebird-base, but as this package was already released recently, you should either wait a month for next release, or get the sources from git repository.
