### ISSUE TITLE
firebird.driver.connect(dsn='host:/path/database.db') unexpected keyword argument 'dsn'

### ISSUE THREAD

**Issue by shvilime** [FirebirdSQL/python3-driver#15]
Is it possible to use param dsn in firebird.driver.connect, like describes on this [doc page](https://firebird-driver.readthedocs.io/en/latest/python-db-api-compliance.html) or is it problem with old documentation ?

**Comment by shvilime** [comment]
the same problem with parameter - sql_dialect/dialect

**Comment by pcisar** [comment]
It's the problem with documentation. Obviously, the examples in "Compliance to PyDB API 2.0" were not updated. The most authoritative documentation source is "Reference", followed by "Usage Guide".
