### ISSUE TITLE
Is there something like fetchonemap, like from the legacy fdb driver?

### ISSUE THREAD

**Issue by ferulisses** [FirebirdSQL/python3-driver#26]
I would like to get a dict as result, or to know which columns has been returned when using a generic SELECTs such as SELECT * FROM customer.

**Comment by pcisar** [comment]
Since version 1.7.0 the helper method [Cursor.to_dict()](https://firebird-driver.readthedocs.io/en/latest/ref-core.html#firebird.driver.core.Cursor.to_dict) is available.
