### ISSUE TITLE
Firebird4 and SQLAlchemy 

### ISSUE THREAD

**Issue by kelsa-pi** [FirebirdSQL/python3-driver#5]
Is there support in SQLAlchemy 1.4 for Firebird 4 and python3-driver?

**Comment by pcisar** [comment]
AFAIK SQLAlchemy 1.4 still uses FDB, not firebird-driver. But it shouldn't be a big problem to add support for firebird-driver as it's Python Database API 2.0-compliant driver like FDB. Ask in SQLAlchemy support & development forums.
