### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by mrx23dot** [FirebirdSQL/python3-driver#6]
Python 3.8+ requirements is quite restrictive,
e.g. current Amazon AWS VPS servers come with Python 3.7.3

RasperryPi-s max out at v3.5 (after apt-get)

What's the bottleneck for not using v3.6 or v3.5?

**Comment by pcisar** [comment]
Because it uses features from 3.8 not present in 3.6/3.7. If you need support of older Python versions (including 2.7), you may use the legacy [FDB driver](https://github.com/FirebirdSQL/fdb). Given that current stable version is 3.10, requirement for 3.8 is not that far-fetched.

**Comment by mrx23dot** [comment]
Thank you, a link to FDB would be nice in readme pages/pypi for anyone using the older one.

Where can I download **Firebird client library** for windows? I couldn't find it, and FDB expects it, I guess this lib too.

**Comment by pcisar** [comment]
Firebird client library is part of Firebird distribution, so just [download](https://www.ibphoenix.com/download/firebird/40) one you need.
